import { NextResponse } from "next/server";
import { z } from "zod";
import { hasPermission } from "@dantown/auth";
import { applyApprovedPricingRecommendation } from "@dantown/database";
import { getAuthorizationContext } from "@/lib/auth/server";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";const approvalSchema = z.object({recommendationId : z.string().uuid("Recommendation ID is invalid."),decision: z.enum(["approve", "reject"]).default("approve"),reviewNote : z.union([z.string().trim().max(500), z.literal(""), z.null()]).optional().transform((value) => value === "" || value === null ? null : value)
});async function parseApprovalPayload(request : Request) {const contentType = request.headers.get("content-type") ?? "";if (contentType.includes("application/json")) {return request.json();}const formData = await request.formData();return {recommendationId : formData.get("recommendationId"),decision : formData.get("decision") ?? "approve",reviewNote : formData.get("reviewNote") ?? null};
}export async function POST(request : Request) {const context = await getAuthorizationContext();if (!context) {return NextResponse.json({ error : "Authentication required." }, { status: 401 });}if (!hasPermission(context, "pricing.approve")) {return NextResponse.json({ error : "You do not have permission to approve pricing changes." }, { status: 403 });}try {const rawBody = await parseApprovalPayload(request);const payload = approvalSchema.parse(rawBody);const supabase = createSupabaseAdminClient();const result = await applyApprovedPricingRecommendation(supabase, {recommendationId : payload.recommendationId,decision : payload.decision,reviewNote : payload.reviewNote,approvedBy : context.userId});const isFormSubmission = (request.headers.get("content-type") ?? "").includes("application/x-www-form-urlencoded");if (isFormSubmission) {const redirectUrl = new URL(`/admin/automation/pricingstatus=${payload.decision}`, request.url);return NextResponse.redirect(redirectUrl);}return NextResponse.json({ ok : true, data: result }, { status: 200 });} catch (error) {if (error instanceof z.ZodError) {return NextResponse.json({ error : "Please provide a valid recommendation and decision.", details: error.issues }, { status: 400 });}console.error("Failed to process pricing approval.", error);return NextResponse.json({ error : error instanceof Error ? error.message : "Failed to process pricing approval." }, { status: 500 });}
}
