insert into public.categories (name, slug, description, sort_order, is_active) values
('Cables & Wires','cables-wires','Reliable conductors for residential and commercial work.',1,true), ('Switches','switches','Everyday and premium switching solutions.',2,true), ('Sockets','sockets','Safe, durable power access.',3,true), ('Plugs','plugs','Plugs and adaptors for every installation.',4,true), ('Circuit Protection','circuit-protection','MCBs, RCCBs and protection devices.',5,true), ('Distribution Boards','distribution-boards','Organize and protect your circuits.',6,true), ('Lighting','lighting','Purposeful lighting for every environment.',7,true), ('LED Bulbs','led-bulbs','Efficient everyday illumination.',8,true), ('Downlights','downlights','Clean recessed lighting.',9,true), ('Floodlights','floodlights','High-output outdoor lighting.',10,true), ('Outdoor Lighting','outdoor-lighting','Light built for the elements.',11,true), ('Electrical Accessories','electrical-accessories','The finishing details of a good installation.',12,true), ('Conduits','conduits','Protect and route electrical cable.',13,true), ('Cable Management','cable-management','Keep every run clean and serviceable.',14,true), ('Earthing','earthing','Grounding and safety essentials.',15,true), ('Tools','tools','Professional tools for electrical work.',16,true), ('Solar & Power','solar-power','Practical independent power solutions.',17,true), ('Smart Home','smart-home','Connected control for modern spaces.',18,true), ('Security & CCTV','security-cctv','Visibility and peace of mind.',19,true), ('Industrial Electrical','industrial-electrical','Components for demanding environments.',20,true), ('Construction Electrical','construction-electrical','Site-ready electrical essentials.',21,true)
on conflict (slug) do nothing;
insert into public.brands (name, slug, description, is_active) values
('Dantown Demo','dantown-demo','Development seed brand. Not a live manufacturer.',true), ('Schneider Electric Demo','schneider-demo','Development seed record for testing only.',true), ('Philips Demo','philips-demo','Development seed record for testing only.',true), ('Hager Demo','hager-demo','Development seed record for testing only.',true)
on conflict (slug) do nothing;
insert into public.warehouses (name, code, location, description) values ('Kitale Main Store','KTL-01','Kitale, Kenya','Development seed warehouse. Stock is not real inventory.') on conflict (code) do nothing;
insert into public.products (sku, barcode, name, slug, short_description, category_id, brand_id, cost_price, retail_price, contractor_price, vat_rate, warranty_period, status, featured, is_active, seo_title, seo_description)
select x.sku, x.barcode, x.name, x.slug, x.short_description, c.id, b.id, x.cost_price, x.retail_price, x.contractor_price, 16, x.warranty_period, 'ACTIVE', x.featured, true, x.name || ' | Dantown Demo', 'Development seed product. Not live inventory.'
from (values
('DEMO-CBL-15','990000000001','1.5mm² Twin Cable','demo-1-5mm-twin-cable','Development sample cable for testing.', 'cables-wires','dantown-demo',850.00,1200.00,1050.00,12,false),
('DEMO-CBL-25','990000000002','2.5mm² Twin Cable','demo-2-5mm-twin-cable','Development sample cable for testing.', 'cables-wires','dantown-demo',1500.00,2100.00,1850.00,12,false),
('DEMO-LGT-9W','990000000003','9W LED Downlight','demo-9w-led-downlight','Development sample downlight for testing.', 'downlights','philips-demo',420.00,650.00,560.00,24,true),
('DEMO-SKT-13A','990000000004','13A Switched Socket','demo-13a-switched-socket','Development sample socket for testing.', 'sockets','schneider-demo',550.00,850.00,760.00,24,true),
('DEMO-MCB-32A','990000000005','32A Single Pole MCB','demo-32a-single-pole-mcb','Development sample protection device.', 'circuit-protection','hager-demo',450.00,780.00,690.00,24,true),
('DEMO-FLD-50W','990000000006','50W LED Floodlight','demo-50w-led-floodlight','Development sample floodlight for testing.', 'floodlights','philips-demo',2400.00,3850.00,3400.00,24,true),
('DEMO-CND-20M','990000000007','20mm PVC Conduit','demo-20mm-pvc-conduit','Development sample conduit for testing.', 'conduits','dantown-demo',95.00,150.00,125.00,12,false)
) as x(sku,barcode,name,slug,short_description,category_slug,brand_slug,cost_price,retail_price,contractor_price,warranty_period,featured)
join public.categories c on c.slug = x.category_slug join public.brands b on b.slug = x.brand_slug
on conflict (sku) do nothing;
