export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      departments: { Row: Department; Insert: DepartmentInsert; Update: Partial<DepartmentInsert>; Relationships: [] };
      categories: { Row: Category; Insert: CategoryInsert; Update: Partial<CategoryInsert>; Relationships: [] };
      brands: { Row: Brand; Insert: BrandInsert; Update: Partial<BrandInsert>; Relationships: [] };
      product_images: { Row: ProductImage; Insert: ProductImageInsert; Update: Partial<ProductImageInsert>; Relationships: [] };
      product_variants: { Row: ProductVariant; Insert: ProductVariantInsert; Update: Partial<ProductVariantInsert>; Relationships: [] };
      product_specifications: { Row: ProductSpecification; Insert: ProductSpecificationInsert; Update: Partial<ProductSpecificationInsert>; Relationships: [] };
      products: { Row: Product; Insert: ProductInsert; Update: Partial<ProductInsert>; Relationships: [] };
      inventory: { Row: Inventory; Insert: InventoryInsert; Update: Partial<InventoryInsert>; Relationships: [] };
      inventory_movements: { Row: InventoryMovement; Insert: InventoryMovementInsert; Update: Partial<InventoryMovementInsert>; Relationships: [] };
      warehouses: { Row: Warehouse; Insert: WarehouseInsert; Update: Partial<WarehouseInsert>; Relationships: [] };
      suppliers: { Row: Supplier; Insert: SupplierInsert; Update: Partial<SupplierInsert>; Relationships: [] };
      supplier_products: { Row: SupplierProduct; Insert: SupplierProductInsert; Update: Partial<SupplierProductInsert>; Relationships: [] };
      purchase_orders: { Row: PurchaseOrder; Insert: PurchaseOrderInsert; Update: Partial<PurchaseOrderInsert>; Relationships: [] };
      purchase_order_items: { Row: PurchaseOrderItem; Insert: PurchaseOrderItemInsert; Update: Partial<PurchaseOrderItemInsert>; Relationships: [] };
      product_drafts: { Row: ProductDraft; Insert: ProductDraftInsert; Update: Partial<ProductDraftInsert>; Relationships: [] };
      orders: { Row: Order; Insert: OrderInsert; Update: Partial<OrderInsert>; Relationships: [] };
      order_items: { Row: OrderItem; Insert: OrderItemInsert; Update: Partial<OrderItemInsert>; Relationships: [] };
      payments: { Row: Payment; Insert: PaymentInsert; Update: Partial<PaymentInsert>; Relationships: [] };
      pos_sessions: { Row: PosSession; Insert: PosSessionInsert; Update: Partial<PosSessionInsert>; Relationships: [] };
      pos_sync_records: { Row: PosSyncRecord; Insert: PosSyncRecordInsert; Update: Partial<PosSyncRecordInsert>; Relationships: [] };
      ai_knowledge_entries: { Row: AiKnowledgeEntry; Insert: AiKnowledgeEntryInsert; Update: Partial<AiKnowledgeEntryInsert>; Relationships: [] };
      ai_support_escalations: { Row: AiSupportEscalation; Insert: AiSupportEscalationInsert; Update: Partial<AiSupportEscalationInsert>; Relationships: [] };
      quotations: { Row: Quotation; Insert: QuotationInsert; Update: Partial<QuotationInsert>; Relationships: [] };
      roles: { Row: Role; Insert: RoleInsert; Update: Partial<RoleInsert>; Relationships: [] };
      permissions: { Row: PermissionRow; Insert: PermissionInsert; Update: Partial<PermissionInsert>; Relationships: [] };
      user_roles: { Row: UserRoleRow; Insert: UserRoleInsert; Update: Partial<UserRoleInsert>; Relationships: [] };
      role_permissions: { Row: RolePermissionRow; Insert: RolePermissionInsert; Update: Partial<RolePermissionInsert>; Relationships: [] };
      profiles: { Row: Profile; Insert: ProfileInsert; Update: Partial<ProfileInsert>; Relationships: [] };
      customers: { Row: Customer; Insert: CustomerInsert; Update: Partial<CustomerInsert>; Relationships: [] };
      customer_addresses: { Row: CustomerAddress; Insert: CustomerAddressInsert; Update: Partial<CustomerAddressInsert>; Relationships: [] };
      carts: { Row: Cart; Insert: CartInsert; Update: Partial<CartInsert>; Relationships: [] };
      cart_items: { Row: CartItemRow; Insert: CartItemInsert; Update: Partial<CartItemInsert>; Relationships: [] };
      wishlists: { Row: Wishlist; Insert: WishlistInsert; Update: Partial<WishlistInsert>; Relationships: [] };
      wishlist_items: { Row: WishlistItem; Insert: WishlistItemInsert; Update: Partial<WishlistItemInsert>; Relationships: [] };
      audit_logs: { Row: AuditLog; Insert: AuditLogInsert; Update: Partial<AuditLogInsert>; Relationships: [] };
      notification_preferences: { Row: NotificationPreference; Insert: NotificationPreferenceInsert; Update: Partial<NotificationPreferenceInsert>; Relationships: [] };
      notifications: { Row: Notification; Insert: NotificationInsert; Update: Partial<NotificationInsert>; Relationships: [] };
      automation_jobs: { Row: AutomationJob; Insert: AutomationJobInsert; Update: Partial<AutomationJobInsert>; Relationships: [] };
      product_matches: { Row: ProductMatch; Insert: ProductMatchInsert; Update: Partial<ProductMatchInsert>; Relationships: [] };
      landed_cost_calculations: { Row: LandedCostCalculation; Insert: LandedCostCalculationInsert; Update: Partial<LandedCostCalculationInsert>; Relationships: [] };
      pricing_recommendations: { Row: PricingRecommendationRow; Insert: PricingRecommendationInsert; Update: Partial<PricingRecommendationInsert>; Relationships: [] };
      pricing_approvals: { Row: PricingApproval; Insert: PricingApprovalInsert; Update: Partial<PricingApprovalInsert>; Relationships: [] };
      price_history: { Row: PriceHistory; Insert: PriceHistoryInsert; Update: Partial<PriceHistoryInsert>; Relationships: [] };
    };
    Views: { inventory_health: { Row: InventoryHealth; Relationships: [] } };
    Functions: { adjust_inventory: { Args: { target_product_id: string; target_warehouse_id: string; delta: number; target_movement_type: InventoryMovementType; target_reference_type?: string; target_reference_id?: string }; Returns: Inventory }; receive_purchase_order_item: { Args: { target_purchase_order_id: string; target_item_id: string; target_received_quantity: number; target_reference_id: string }; Returns: Json }; transfer_inventory: { Args: { target_product_id: string; target_source_warehouse_id: string; target_destination_warehouse_id: string; target_quantity: number; target_reference_id: string }; Returns: Json }; complete_pos_sale: { Args: { sale_order_number: string; sale_customer_id: string | null; sale_subtotal: number; sale_vat: number; sale_total: number; sale_payment_method: "MPESA" | "CASH" | "CARD" | "BANK_TRANSFER" | "PAY_ON_PICKUP" | "COD"; sale_staff_user_id: string | null; sale_staff_name: string; sale_staff_role: string; sale_items: Json }; Returns: Order }; complete_pos_sale_split: { Args: { sale_order_number: string; sale_customer_id: string | null; sale_subtotal: number; sale_vat: number; sale_total: number; sale_payment_method: "MPESA" | "CASH" | "CARD" | "BANK_TRANSFER"; sale_staff_user_id: string | null; sale_staff_name: string; sale_staff_role: string; sale_items: Json; sale_split_payments: Json }; Returns: Order }; create_pos_paystack_order: { Args: { sale_customer_id: string | null; sale_customer_name: string; sale_staff_user_id: string | null; sale_staff_name: string; sale_staff_role: string; sale_items: Json }; Returns: Order }; complete_pos_paystack_payment: { Args: { target_order_id: string; target_provider_reference: string; provider_amount: number; provider_payload: Json }; Returns: Order }; create_online_order: { Args: { order_number: string; buyer_user_id: string | null; customer_name: string; customer_phone: string; customer_email: string | null; fulfillment_type: string; shipping_details: Json; delivery_fee: number; requested_items: Json }; Returns: Order }; release_online_order: { Args: { order_id: string; release_reason?: string }; Returns: Order }; process_return: { Args: { order_id: string; refund_reason: string; refund_amount: number; staff_user_id: string | null }; Returns: Json } };
    Enums: { order_status: OrderStatus; payment_status: PaymentStatus; inventory_movement_type: InventoryMovementType };
    CompositeTypes: {};
  };
};

export type Product = { 
  id: string; 
  sku: string; 
  barcode: string | null; 
  name: string; 
  slug: string;
  short_description: string | null;
  description: string | null;
  category_id: string | null;
  brand_id: string | null;
  cost_price: number;
  retail_price: number; 
  contractor_price: number | null; 
  wholesale_price: number | null;
  dealer_price: number | null;
  promotional_price: number | null;
  promotion_label: string | null;
  promotion_starts_at: string | null;
  promotion_ends_at: string | null;
  vat_rate: number; 
  is_active: boolean; 
  status: string;
  featured: boolean;
  weight: number | null;
  length: number | null;
  width: number | null;
  height: number | null;
  warranty_period: number | null;
  seo_title: string | null;
  seo_description: string | null;
  created_by: string | null;
  updated_by: string | null;
  created_at: string;
  updated_at: string;
  product_type: string | null;
  internal_code: string | null;
  manufacturer_part_number: string | null;
  tags: string[];
  attributes: Json;
  unit_of_measure: string;
  minimum_selling_price: number | null;
  maximum_suggested_price: number | null;
  tax_inclusive: boolean;
};
export type ProductInsert = Omit<Product, "id" | "product_type" | "internal_code" | "manufacturer_part_number" | "tags" | "attributes" | "unit_of_measure" | "minimum_selling_price" | "maximum_suggested_price" | "tax_inclusive" | "promotion_label" | "promotion_starts_at" | "promotion_ends_at"> & {
  id?: string;
  product_type?: string | null;
  internal_code?: string | null;
  manufacturer_part_number?: string | null;
  tags?: string[];
  attributes?: Json;
  unit_of_measure?: string;
  minimum_selling_price?: number | null;
  maximum_suggested_price?: number | null;
  tax_inclusive?: boolean;
  promotion_label?: string | null;
  promotion_starts_at?: string | null;
  promotion_ends_at?: string | null;
};

export type Category = {
  id: string;
  name: string;
  slug: string;
  description: string | null;
  image_url: string | null;
  parent_id: string | null;
  sort_order: number;
  is_active: boolean;
  seo_title: string | null;
  seo_description: string | null;
  created_at: string;
  updated_at: string;
  department_id: string | null;
  icon: string | null;
};
export type CategoryInsert = Omit<Category, "id" | "department_id" | "icon"> & { id?: string; department_id?: string | null; icon?: string | null };

export type Brand = {
  id: string;
  name: string;
  slug: string;
  description: string | null;
  logo_url: string | null;
  website: string | null;
  is_active: boolean;
  seo_title: string | null;
  seo_description: string | null;
  created_at: string;
  updated_at: string;
  image_url: string | null;
  country_of_origin: string | null;
  supplier_relationship: string | null;
};
export type BrandInsert = Omit<Brand, "id" | "image_url" | "country_of_origin" | "supplier_relationship"> & { id?: string; image_url?: string | null; country_of_origin?: string | null; supplier_relationship?: string | null };

export type ProductImage = {
  id: string;
  product_id: string;
  image_url: string;
  alt_text: string | null;
  sort_order: number;
  is_primary: boolean;
  created_at: string;
};
export type ProductImageInsert = Omit<ProductImage, "id"> & { id?: string };
export type ProductVariant = {
  id: string;
  product_id: string;
  sku: string;
  barcode: string | null;
  name: string;
  attributes: Json;
  price_adjustment: number;
  cost_price: number | null;
  retail_price: number | null;
  wholesale_price: number | null;
  weight: number | null;
  image_url: string | null;
  specifications: Json;
  is_active: boolean;
  created_at: string;
  updated_at: string;
};
export type ProductVariantInsert = Omit<ProductVariant, "id" | "barcode" | "cost_price" | "retail_price" | "wholesale_price" | "weight" | "image_url" | "specifications" | "created_at" | "updated_at"> & {
  id?: string;
  barcode?: string | null;
  cost_price?: number | null;
  retail_price?: number | null;
  wholesale_price?: number | null;
  weight?: number | null;
  image_url?: string | null;
  specifications?: Json;
  created_at?: string;
  updated_at?: string;
};
export type ProductSpecification = {
  id: string;
  product_id: string;
  specification_name: string;
  specification_value: string;
  sort_order: number;
};
export type ProductSpecificationInsert = Omit<ProductSpecification, "id"> & { id?: string };
export type Department = {
  id: string;
  name: string;
  slug: string;
  description: string | null;
  image_url: string | null;
  icon: string | null;
  sort_order: number;
  is_active: boolean;
  created_at: string;
  updated_at: string;
};
export type DepartmentInsert = Omit<Department, "id"> & { id?: string };
export type Inventory = { id: string; product_id: string; variant_id: string | null; warehouse_id: string; location_id: string | null; quantity: number; reserved_quantity: number; reorder_level: number; reorder_quantity: number };
export type InventoryInsert = Omit<Inventory, "id" | "variant_id" | "location_id"> & { id?: string; variant_id?: string | null; location_id?: string | null };
export type InventoryMovement = { id: string; product_id: string; warehouse_id: string; quantity: number; movement_type: InventoryMovementType; created_at: string };
export type InventoryMovementInsert = Omit<InventoryMovement, "id" | "created_at"> & { id?: string; created_at?: string };
export type Warehouse = { id: string; name: string; code: string; location: string | null; description: string | null; manager_id: string | null; is_active: boolean; created_at: string; updated_at: string };
export type WarehouseInsert = Omit<Warehouse, "id" | "created_at" | "updated_at"> & { id?: string; created_at?: string; updated_at?: string };
export type Supplier = { id: string; company_name: string; contact_name: string | null; phone: string | null; email: string | null; address: string | null; tax_number: string | null; payment_terms: string | null; status: "ACTIVE" | "INACTIVE" | "BLACKLISTED"; created_at: string; updated_at: string };
export type SupplierInsert = Omit<Supplier, "id" | "created_at" | "updated_at"> & { id?: string; created_at?: string; updated_at?: string };
export type SupplierProduct = { supplier_id: string; product_id: string; supplier_sku: string | null; unit_cost: number; lead_time_days: number | null };
export type SupplierProductInsert = SupplierProduct;
export type PurchaseOrder = { id: string; order_number: string; supplier_id: string; warehouse_id: string; status: string; subtotal: number; tax: number; total: number; expected_at: string | null; created_by: string | null; approved_by: string | null; created_at: string; updated_at: string };
export type PurchaseOrderInsert = Omit<PurchaseOrder, "id" | "created_at" | "updated_at"> & { id?: string; created_at?: string; updated_at?: string };
export type PurchaseOrderItem = { id: string; purchase_order_id: string; product_id: string; quantity: number; received_quantity: number; unit_cost: number };
export type PurchaseOrderItemInsert = Omit<PurchaseOrderItem, "id"> & { id?: string };
export type ProductDraft = { id: string; status: string; created_at: string; updated_at: string };
export type ProductDraftInsert = Omit<ProductDraft, "id" | "created_at" | "updated_at"> & { id?: string; created_at?: string; updated_at?: string };
export type InventoryHealth = Inventory & { available_quantity: number; is_low_stock: boolean };
export type OrderStatus = "PENDING" | "PAYMENT_PENDING" | "PAID" | "PROCESSING" | "READY_FOR_PICKUP" | "READY_FOR_DELIVERY" | "OUT_FOR_DELIVERY" | "DELIVERED" | "CANCELLED" | "REFUNDED" | "PARTIALLY_REFUNDED" | "FAILED";
export type PaymentStatus = "PENDING" | "PROCESSING" | "SUCCESS" | "FAILED" | "CANCELLED" | "REFUNDED" | "PARTIALLY_REFUNDED";
export type InventoryMovementType = "PURCHASE" | "SALE" | "RETURN" | "ADJUSTMENT" | "TRANSFER_IN" | "TRANSFER_OUT" | "DAMAGE" | "STOCK_COUNT" | "RESERVATION" | "RELEASE";
export type Order = { 
  id: string; 
  order_number: string; 
  customer_id: string | null; 
  subtotal: number; 
  discount: number; 
  vat: number; 
  delivery_fee: number; 
  total: number; 
  payment_status: PaymentStatus; 
  order_status: OrderStatus;
  sales_channel: "ONLINE" | "POS";
  processed_by_user_id: string | null;
  processed_by_staff_name: string | null;
  processed_by_staff_role: string | null;
  offline_transaction_id: string | null;
  offline_device_id: string | null;
  offline_sync_status: "PENDING" | "SYNCING" | "SYNCED" | "FAILED" | "CONFLICT" | null;
  offline_retry_count: number;
  offline_sync_error: string | null;
  offline_synced_at: string | null;
  shipping_address: Json | null;
  billing_address: Json | null;
  notes: string | null;
  created_by: string | null;
  created_at: string;
  updated_at: string;
};
export type OrderInsert = {
  id?: string;
  order_number: string;
  customer_id?: string | null;
  subtotal: number;
  discount?: number;
  vat?: number;
  delivery_fee?: number;
  total: number;
  payment_status?: PaymentStatus;
  order_status?: OrderStatus;
  sales_channel?: "ONLINE" | "POS";
  processed_by_user_id?: string | null;
  processed_by_staff_name?: string | null;
  processed_by_staff_role?: string | null;
  offline_transaction_id?: string | null;
  offline_device_id?: string | null;
  offline_sync_status?: "PENDING" | "SYNCING" | "SYNCED" | "FAILED" | "CONFLICT" | null;
  offline_retry_count?: number;
  offline_sync_error?: string | null;
  offline_synced_at?: string | null;
  shipping_address?: Json | null;
  billing_address?: Json | null;
  notes?: string | null;
};
export type OrderItem = { 
  id: string; 
  order_id: string; 
  product_id: string | null; 
  variant_id: string | null;
  product_name_snapshot: string; 
  sku_snapshot: string; 
  unit_price: number; 
  quantity: number; 
  discount: number; 
  vat: number; 
  line_total: number 
};
export type OrderItemInsert = Omit<OrderItem, "id"> & { id?: string };
export type Payment = { id: string; order_id: string; method: "MPESA" | "CASH" | "CARD" | "BANK_TRANSFER" | "PAY_ON_PICKUP" | "COD"; status: PaymentStatus; amount: number; currency: string; provider: string | null; created_at: string; updated_at: string };
export type PaymentInsert = Omit<Payment, "id" | "created_at" | "updated_at" | "currency" | "provider"> & { id?: string; currency?: string; provider?: string | null };
export type PosSession = { id: string; employee_id: string; warehouse_id: string; status: "OPEN" | "CLOSED"; opening_balance: number; closing_balance: number | null; opened_at: string; closed_at: string | null };
export type PosSessionInsert = Omit<PosSession, "id"> & { id?: string };
export type PosSyncStatus = "PENDING" | "SYNCING" | "SYNCED" | "FAILED" | "CONFLICT";
export type PosSyncRecord = { transaction_id: string; device_id: string; staff_user_id: string | null; status: PosSyncStatus; payload: Json; order_id: string | null; retry_count: number; error_message: string | null; created_at: string; synced_at: string | null };
export type PosSyncRecordInsert = Omit<PosSyncRecord, "created_at" | "synced_at"> & { created_at?: string; synced_at?: string | null };
export type AiKnowledgeStatus = "DRAFT" | "PUBLISHED" | "ARCHIVED";
export type AiKnowledgeEntry = { id: string; title: string; content: string; category: string; status: AiKnowledgeStatus; created_by: string | null; updated_by: string | null; created_at: string; updated_at: string };
export type AiKnowledgeEntryInsert = Omit<AiKnowledgeEntry, "id" | "created_at" | "updated_at"> & { id?: string; created_at?: string; updated_at?: string };
export type AiEscalationStatus = "OPEN" | "ASSIGNED" | "RESOLVED" | "CLOSED";
export type AiSupportEscalation = { id: string; user_id: string | null; guest_session_id: string | null; category: string; summary: string; priority: "LOW" | "NORMAL" | "HIGH" | "URGENT"; status: AiEscalationStatus; assigned_to: string | null; created_at: string; resolved_at: string | null };
export type AiSupportEscalationInsert = Omit<AiSupportEscalation, "id" | "created_at" | "resolved_at"> & { id?: string; created_at?: string; resolved_at?: string | null };
export type Quotation = {
  id: string;
  quote_number: string;
  customer_id: string | null;
  status: "DRAFT" | "SENT" | "VIEWED" | "ACCEPTED" | "REJECTED" | "EXPIRED" | "CONVERTED";
  subtotal: number;
  discount: number;
  vat: number;
  delivery_fee: number;
  total: number;
  valid_until: string | null;
  terms: string | null;
  notes: string | null;
  converted_order_id: string | null;
  created_by: string | null;
  created_at: string;
  updated_at: string;
};
export type QuotationInsert = Omit<Quotation, "id"> & { id?: string };
export type Role = { id: string; code: string; name: string; description: string | null };
export type RoleInsert = Omit<Role, "id"> & { id?: string };
export type PermissionRow = { id: string; code: string; description: string | null };
export type PermissionInsert = Omit<PermissionRow, "id"> & { id?: string };
export type UserRoleRow = { user_id: string; role_id: string; assigned_by: string | null };
export type UserRoleInsert = Omit<UserRoleRow, "assigned_by"> & { assigned_by?: string | null };
export type RolePermissionRow = { role_id: string; permission_id: string };
export type RolePermissionInsert = RolePermissionRow;
export type Profile = {
  id: string;
  full_name: string | null;
  phone: string | null;
  avatar_url: string | null;
  status: "ACTIVE" | "INACTIVE" | "SUSPENDED";
  created_at: string;
  updated_at: string;
};
export type ProfileInsert = {
  id: string;
  full_name?: string | null;
  phone?: string | null;
  avatar_url?: string | null;
  status?: "ACTIVE" | "INACTIVE" | "SUSPENDED";
};
export type Cart = {
  id: string;
  user_id: string | null;
  customer_id: string | null;
  created_at: string;
  updated_at: string;
};
export type CartInsert = {
  id?: string;
  user_id?: string | null;
  customer_id?: string | null;
};
export type CartItemRow = {
  id: string;
  cart_id: string;
  product_id: string;
  variant_id: string | null;
  quantity: number;
  created_at: string;
  updated_at: string;
};
export type CartItemInsert = {
  id?: string;
  cart_id: string;
  product_id: string;
  variant_id?: string | null;
  quantity: number;
};
export type Wishlist = {
  id: string;
  user_id: string;
  created_at: string;
};
export type WishlistInsert = Omit<Wishlist, "id"> & { id?: string };
export type WishlistItem = {
  wishlist_id: string;
  product_id: string;
  created_at: string;
};
export type WishlistItemInsert = WishlistItem;
export type Customer = { 
  id: string; 
  user_id: string | null; 
  name: string; 
  phone: string | null; 
  email: string | null; 
  customer_type: "RETAIL" | "CONTRACTOR" | "WHOLESALE" | "DEALER" | "CORPORATE"; 
  status: "ACTIVE" | "INACTIVE" | "SUSPENDED";
  tax_number: string | null;
  notes: string | null;
  credit_limit: number;
  customer_group_id: string | null;
  created_at: string;
  updated_at: string;
};
export type CustomerInsert = {
  id?: string;
  user_id?: string | null;
  name: string;
  phone?: string | null;
  email?: string | null;
  customer_type?: "RETAIL" | "CONTRACTOR" | "WHOLESALE" | "DEALER" | "CORPORATE";
  status?: "ACTIVE" | "INACTIVE" | "SUSPENDED";
  tax_number?: string | null;
  notes?: string | null;
  credit_limit?: number;
  customer_group_id?: string | null;
};
export type CustomerAddress = {
  id: string;
  customer_id: string;
  label: string;
  recipient_name: string;
  phone: string | null;
  address_line_1: string;
  address_line_2: string | null;
  city: string | null;
  county: string | null;
  postal_code: string | null;
  is_default: boolean;
  created_at: string;
  updated_at: string;
};
export type CustomerAddressInsert = {
  id?: string;
  customer_id: string;
  label?: string;
  recipient_name: string;
  phone?: string | null;
  address_line_1: string;
  address_line_2?: string | null;
  city?: string | null;
  county?: string | null;
  postal_code?: string | null;
  is_default?: boolean;
};
export type AuditLog = { id: string; user_id: string | null; action: string; resource_type: string; resource_id: string | null; old_data: Json | null; new_data: Json | null };
export type AuditLogInsert = Omit<AuditLog, "id" | "old_data" | "new_data"> & { id?: string; old_data?: Json | null; new_data?: Json | null };
export type NotificationPreference = { user_id: string; email: boolean; sms: boolean; whatsapp: boolean; push: boolean; updated_at: string };
export type NotificationPreferenceInsert = Omit<NotificationPreference, "updated_at"> & { updated_at?: string };
export type Notification = { id: string; user_id: string; type: "ORDER" | "PAYMENT" | "DELIVERY" | "LOW_STOCK" | "QUOTE" | "SYSTEM" | "PROMOTION"; title: string; body: string; data: Json; read_at: string | null; created_at: string };
export type NotificationInsert = Omit<Notification, "id" | "created_at"> & { id?: string; created_at?: string };
export type AutomationJob = { id: string; workflow_name: string; status: "RECEIVED" | "PROCESSING" | "COMPLETED" | "PROCESSING_FAILED" | "REQUIRES_REVIEW"; source: string; source_reference: string | null; payload: Json; error_message: string | null; retry_count: number; next_retry_at: string | null; dead_letter: boolean; created_at: string; updated_at: string; completed_at: string | null };
export type AutomationJobInsert = {
  id?: string;
  workflow_name: string;
  status?: AutomationJob["status"];
  source: string;
  source_reference?: string | null;
  payload: Json;
  error_message?: string | null;
  retry_count?: number;
  next_retry_at?: string | null;
  dead_letter?: boolean;
  completed_at?: string | null;
};
export type ProductMatch = { id: string; automation_job_id: string | null; product_id: string | null; supplier_id: string | null; supplier_sku: string | null; source_name: string; normalized_name: string; match_status: "MATCHED" | "POSSIBLE_MATCH" | "NEW_PRODUCT"; confidence: number; match_reasons: Json; reviewed_by: string | null; created_at: string; reviewed_at: string | null };
export type ProductMatchInsert = Omit<ProductMatch, "id" | "created_at" | "reviewed_at"> & { id?: string; reviewed_at?: string | null; created_at?: string; reviewed_by?: string | null };
export type LandedCostCalculation = { id: string; product_id: string | null; supplier_id: string | null; automation_job_id: string | null; unit_cost: number; allocated_transport: number; other_costs: number; supplier_discount: number; tax_amount: number; tax_included: boolean; landed_cost: number; currency: string; inputs: Json };
export type LandedCostCalculationInsert = Omit<LandedCostCalculation, "id"> & { id?: string };
export type PricingRecommendationRow = { id: string; product_id: string | null; landed_cost_calculation_id: string | null; pricing_rule_id: string | null; retail_price: number; contractor_price: number; dealer_price: number; wholesale_price: number; promotional_price: number; minimum_allowed_price: number; maximum_suggested_price: number; reasoning_summary: string; confidence: number; rules_passed: boolean; status: string };
export type PricingRecommendationInsert = Omit<PricingRecommendationRow, "id"> & { id?: string };
export type PricingApprovalStatus = "PENDING" | "AI_RECOMMENDED" | "AUTO_APPROVED" | "REQUIRES_REVIEW" | "APPROVED" | "REJECTED" | "PUBLISHED";
export type PricingApproval = { id: string; recommendation_id: string; status: PricingApprovalStatus; submitted_by: string | null; reviewed_by: string | null; review_note: string | null; created_at: string; reviewed_at: string | null };
export type PricingApprovalInsert = Omit<PricingApproval, "id" | "created_at" | "reviewed_at"> & { id?: string; reviewed_at?: string | null; created_at?: string };
export type PriceHistory = { id: string; product_id: string; price_type: string; old_price: number | null; new_price: number; reason: string; source: "MANUAL" | "AI" | "SUPPLIER_UPDATE" | "PROMOTION" | "MARKET_UPDATE"; recommendation_id: string | null; approved_by: string | null };
export type PriceHistoryInsert = Omit<PriceHistory, "id"> & { id?: string };
